Repository acmucsd/membership-portal-ui, pull requests merged in 2019-08, with the labels that each got.

#12 Set up Redux
  package.json
  src/index.js
  src/reducers/TempReducer.js
  src/reducers/index.js
  src/store.js
  yarn.lock
Labels: Issue: Setup, PR: Needs Review

#13 Set up testing
  babel.config.js
  jest.config.js
  package.json
  tests/setup/setupTests.js
  tests/setup/tests.test.js
  yarn.lock
Labels: Issue: Setup, PR: Good to Merge

#15 Set up travis and coveralls (Closes #9)
  .travis.yml
  README.md
  package.json
  tests/reducers/TempReducer.test.js
  yarn.lock
Labels: Issue: Setup, PR: Good to Merge, PR: Needs Review

#16 Set up router
  package.json
  src/containers/HomePage/index.jsx
  src/index.js
  src/reducers/index.js
  src/store.js
  yarn.lock
Labels: Issue: Feature, PR: Good to Merge

#38 Circleci setup (Closes #36)
  .circleci/config.yml
Labels: Issue: Setup, PR: Good to Merge

#40 Deleted .travis.yml (Closes #39)
  .travis.yml
Labels: Issue: Setup, PR: Good to Merge

#41 Set up global styles (Closes #22)
  src/styles/fonts.less
  src/styles/vars.less
Labels: Issue: Setup, PR: Good to Merge

#42 Update JSX quotes
  config-overrides.js
  jest.config.js
  prettier.config.js
  src/index.js
  src/reducers/TempReducer.js
  src/reducers/index.js
  tests/reducers/TempReducer.test.js
Labels: Issue: Setup, PR: Good to Merge

#43 Add vertical navigation bar
  package.json
  src/assets/graphics/acm-icon.svg
  src/assets/graphics/dashboard-icon.svg
  src/assets/graphics/discord-icon.svg
  src/assets/graphics/lb-icon.svg
  src/assets/graphics/profile-icon.svg
  src/assets/graphics/swag-icon.svg
  src/components/VerticalNavBar/index.jsx
  src/components/VerticalNavBar/style.less
  src/components/VerticalNavItem/index.jsx
  src/components/VerticalNavItem/style.less
  src/index.js
  src/styles/reset.less
  yarn.lock
Labels: Issue: Feature, PR: Good to Merge

#21 Add ProfileCard (Closes #7)
  config-overrides.js
  package.json
  src/components/ProfileCard/index.jsx
  src/components/ProfileCard/style.less
  yarn.lock
Labels: Issue: Feature, PR: Good to Merge

#44 Add drop down menu
  src/components/NavBarVertical/index.jsx
  src/components/NavBarVertical/style.less
  src/components/NavDropdown/index.jsx
  src/components/NavDropdown/style.less
  src/components/NavListItem/index.jsx
  src/components/NavListItem/style.less
  src/styles/vars.less
Labels: Issue: Feature, PR: Good to Merge

#49 Add horizontal navbar
  src/components/NavBarHorizontal/NavTileItem/index.jsx
  src/components/NavBarHorizontal/NavTileItem/style.less
  src/components/NavBarHorizontal/index.jsx
  src/components/NavBarHorizontal/style.less
  src/components/NavBarVertical/index.jsx
  src/components/NavDropdown/index.jsx
  src/components/NavListItem/index.jsx
  src/components/NavListItem/style.less
Labels: Issue: Feature, PR: Good to Merge

#63 Add general page layout
  package.json
  src/components/Banner/style.less
  src/components/NavBarHorizontal/NavTileItem/style.less
  src/components/NavBarHorizontal/index.jsx
  src/components/NavBarVertical/index.jsx
  src/components/NavBarVertical/style.less
  src/components/NavDropdown/style.less
  src/components/NavProfile/index.jsx
  src/components/NavProfile/style.less
  src/components/PageLayout/index.jsx
  src/components/PageLayout/style.less
  src/containers/AboutPage.jsx
  src/containers/HomePage.jsx
  src/containers/LeaderPage.jsx
  src/containers/ProfilePage.jsx
  src/containers/StorePage.jsx
  src/styles/mixins.less
  src/styles/vars.less
  yarn.lock
Labels: Issue: Feature, PR: Good to Merge

#66 Added Netlify Redirect always to index.html
  public/_redirects
Labels: Issue: Bug, PR: Needs Review, PR: Urgent
