Repository acmucsd/membership-portal-ui, pull requests merged in 2019-10, with the labels that each got.

#136 Removed resetForm()
  src/containers/RegisterForm.jsx
Labels: Issue: Bug, PR: Good to Merge

#137 Event Check in Form handing Enter Key (Closes #129)
  src/components/EventCheckIn/index.jsx
  src/containers/EventCheckIn.jsx
Labels: Issue: Bug, PR: Good to Merge

#138 Password Reset Layout
  src/components/PasswordForm/index.jsx
  src/components/PasswordForm/style.less
  src/components/PasswordReset/index.jsx
  src/components/PasswordReset/style.less
  src/containers/PasswordUpdate.jsx
  src/index.js
  src/styles/vars.less
Labels: Issue: Feature, PR: Good to Merge

#143 Minor Fixes for Profile Card
  src/components/ProfileCard/index.jsx
Labels: Issue: Bug, PR: Good to Merge

#139 Email Password Reset Action
  src/actions/authActions.js
  src/actions/types.js
  src/components/PasswordForm/index.jsx
  src/containers/PasswordPage.jsx
  src/index.js
  src/reducers/index.js
  src/reducers/passwordReducer.js
Labels: Issue: Feature, PR: Good to Merge

#144 fixed edge case with 12th hour
  src/containers/CreateEventForm.jsx
Labels: PR: Good to Merge

#147 Improve Event Check In Modal (Closes #140)
  src/actions/eventsActions.js
  src/actions/types.js
  src/components/Modal/index.jsx
  src/components/Modal/style.less
  src/containers/CheckInModal.jsx
  src/reducers/EventsReducer.js
Labels: Issue: Bug, Issue: Feature, PR: Good to Merge

#146 Password Update
  package-lock.json
  package.json
  src/actions/authActions.js
  src/components/PasswordReset/index.jsx
  src/components/PasswordReset/style.less
  src/containers/PasswordUpdate.jsx
  src/containers/ResetPage.jsx
  src/index.js
Labels: Issue: Bug, PR: Needs Review, PR: Urgent

#149 HR Fixes Horizontal Scrollbar
  src/components/PageLayout/style.less
Labels: Issue: Bug, PR: Good to Merge

#152 Adds Prevent Default
  src/containers/PasswordUpdate.jsx
Labels: Issue: Bug, PR: Needs Review, PR: Urgent
