Repository acmucsd/membership-portal-ui, pull requests merged in 2019-09, with the labels that each got.

#67 Add profile card container
  src/components/ProfileCard/index.jsx
  src/containers/ProfileCard.jsx
Labels: Issue: Feature, PR: Good to Merge

#69 Create store page
  src/assets/icons/swag-icon.svg
  src/components/PageLayout/style.less
  src/components/StorePage/index.jsx
  src/components/StorePage/style.less
  src/containers/StorePage.jsx
Labels: Issue: Feature, PR: Good to Merge

#68 Register Form Layout (Closes #25)
  src/components/RegisterForm/index.jsx
  src/components/RegisterForm/style.less
  src/styles/vars.less
Labels: Issue: Feature, PR: Good to Merge

#74 Temporary Password Reset
  src/components/PasswordForm/index.jsx
  src/components/PasswordForm/style.less
  src/styles/vars.less
Labels: Issue: Feature, PR: Good to Merge

#71 Improve page layout styling
  src/components/NavBarVertical/style.less
  src/components/NavListItem/style.less
  src/components/PageLayout/index.jsx
  src/components/PageLayout/style.less
Labels: Issue: Feature, PR: Good to Merge

#78 Leaderboard Top Card Component
  src/components/TopLeaderCard/index.jsx
  src/components/TopLeaderCard/style.less
  src/containers/LeaderPage.jsx
Labels: Issue: Feature, PR: Good to Merge

#79 Created temp forgot password page
  src/components/RegisterForm/index.jsx
  src/containers/PasswordPage.jsx
  src/index.js
Labels: Issue: Feature, PR: Good to Merge

#77 Add Event CheckIn Container
  src/actions/eventsActions.js
  src/actions/types.js
  src/components/EventCheckIn/index.jsx
  src/containers/EventCheckIn.jsx
  src/reducers/EventsReducer.js
  src/reducers/index.js
Labels: Issue: Feature, PR: Good to Merge

#81 Update banner size
  src/components/Banner/style.less
Labels: Issue: Bug, PR: Needs Review

#80 Add leaderboard list item
  src/components/LeaderListItem/index.jsx
  src/components/LeaderListItem/style.less
  src/components/NavProfile/style.less
  src/components/TopLeaderCard/index.jsx
Labels: Issue: Feature, PR: Good to Merge

#82 Add dashboard to homepage
  src/components/EventCheckIn/index.jsx
  src/components/EventCheckIn/style.less
  src/components/HomePage/index.jsx
  src/components/HomePage/style.less
  src/components/ProfileCard/index.jsx
  src/components/ProfileCard/style.less
  src/containers/HomePage.jsx
  src/reducers/UserReducer.js
  src/styles/vars.less
Labels: Issue: Feature, PR: Good to Merge

#83 Add events containers (Closes #17, #23, and #24)
  package.json
  src/actions/eventsActions.js
  src/actions/types.js
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/index.jsx
  src/components/EventCard/styles.less
  src/components/EventsList/index.jsx
  src/components/EventsList/style.less
  src/components/HomePage/index.jsx
  src/components/HomePage/style.less
  src/components/ProfileCard/style.less
  src/containers/EventCardContainer.jsx
  src/containers/PastEvents.jsx
  src/containers/UpcomingEvents.jsx
  src/reducers/EventsReducer.js
Labels: Issue: Feature, PR: Good to Merge

#87 Add sign in form container (Closes #26)
  package.json
  src/actions/authActions.js
  src/actions/types.js
  src/components/SignInForm/index.jsx
  src/containers/LoginPage.jsx
  src/containers/SignInForm.jsx
  src/reducers/AuthReducer.js
Labels: Issue: Feature, PR: Good to Merge

#89 Add leaderboard container (Closes #28)
  src/actions/leaderboardActions.js
  src/actions/types.js
  src/components/LeaderPage/index.jsx
  src/components/LeaderPage/style.less
  src/components/Leaderboard/index.jsx
  src/components/Leaderboard/style.less
  src/components/TopLeaderCard/style.less
  src/containers/FourAndMore.jsx
  src/containers/LeaderPage.jsx
  src/containers/TopThree.jsx
  src/reducers/LeaderboardReducer.js
  src/reducers/index.js
Labels: Issue: Feature, PR: Good to Merge

#88 Add requireAuth HOC
  src/containers/requireAuth.jsx
  src/index.js
Labels: Issue: Feature, PR: Good to Merge

#95 Update profile component
  src/components/ProfileUpdate/index.jsx
  src/components/ProfileUpdate/style.less
  src/styles/vars.less
Labels: Issue: Feature, PR: Good to Merge

#94 Redirect to home page once authenticated
  src/actions/authActions.js
  src/containers/SignInForm.jsx
  src/reducers/AuthReducer.js
Labels: Issue: Feature, PR: Good to Merge

#96 Authenticate card and container
  src/components/AuthenticateCard/index.jsx
  src/components/AuthenticateCard/style.less
  src/containers/AuthPage.jsx
  src/index.js
Labels: Issue: Feature, PR: Needs Review

#98 Add admin access in navbar
  src/assets/icons/admin-icon.svg
  src/components/NavBarVertical/index.jsx
  src/components/PageLayout/index.jsx
  src/containers/AboutPage.jsx
  src/containers/HomePage.jsx
  src/containers/LeaderPage.jsx
  src/containers/PageLayout.jsx
  src/containers/ProfilePage.jsx
  src/containers/StorePage.jsx
Labels: Issue: Feature, PR: Good to Merge

#100 Have page layout render its children
  src/containers/PageLayout.jsx
Labels: Issue: Bug, PR: Good to Merge

#101 Add create events form
  src/components/AdminPage/index.jsx
  src/components/AdminPage/style.less
  src/components/CreateEventForm/index.jsx
  src/components/CreateEventForm/style.less
  src/containers/AdminPage.jsx
  src/index.js
  src/reducers/AuthReducer.js
  src/styles/vars.less
Labels: Issue: Feature, PR: Good to Merge

#102 Connect admin form to Formik
  src/components/AdminPage/index.jsx
  src/components/CreateEventForm/index.jsx
  src/components/CreateEventForm/style.less
  src/containers/CreateEventForm.jsx
Labels: Issue: Feature, PR: Good to Merge

#99 Register container (Closes #91)
  src/actions/registerActions.js
  src/actions/types.js
  src/components/RegisterForm/index.jsx
  src/components/SignInForm/index.jsx
  src/containers/RegisterForm.jsx
  src/containers/RegisterPage.jsx
  src/reducers/RegisterReducer.js
  src/reducers/index.js
  yarn.lock
Labels: Issue: Feature, PR: Good to Merge

#104 Connect to registration API
  src/actions/registerActions.js
  src/components/RegisterForm/index.jsx
  src/config.js
  src/containers/RegisterForm.jsx
Labels: Issue: Feature, PR: Good to Merge

#107 Connect sign in form to API
  package.json
  src/actions/authActions.js
  src/actions/types.js
  src/containers/SignInForm.jsx
  src/reducers/AuthReducer.js
Labels: Issue: Feature, PR: Good to Merge

#108 Fix register value bug
  src/components/RegisterForm/index.jsx
  src/containers/RegisterForm.jsx
Labels: Issue: Bug, PR: Good to Merge

#109 Add notifications to auth and register
  src/actions/authActions.js
  src/actions/registerActions.js
  src/utils/notifications.js
Labels: Issue: Feature, PR: Good to Merge

#111 Add token storage (Closes #76)
  src/actions/authActions.js
  src/utils/storage.js
Labels: Issue: Feature, PR: Good to Merge

#110 Profile Container
  src/actions/profileActions.js
  src/actions/types.js
  src/components/ProfileUpdate/index.jsx
  src/components/ProfileUpdate/style.less
  src/containers/ProfilePage.jsx
  src/containers/ProfileUpdate.jsx
  src/reducers/ProfileReducer.js
  src/reducers/index.js
Labels: Issue: Feature, PR: Good to Merge

#115 Leaderboard api + CORS Fix
  src/actions/leaderboardActions.js
  src/actions/types.js
  src/components/LeaderListItem/index.jsx
  src/components/TopLeaderCard/index.jsx
  src/config.js
  src/containers/FourAndMore.jsx
  src/containers/TopThree.jsx
  src/reducers/LeaderboardReducer.js
  src/utils/ranks.js
Labels: Issue: Feature, PR: Good to Merge

#117 Use token in cookie
  src/reducers/AuthReducer.js
Labels: Issue: Feature, PR: Good to Merge

#116 Add default profile picture (Closes #106)
  src/actions/authActions.js
  src/actions/leaderboardActions.js
  src/actions/registerActions.js
  src/actions/userActions.js
  src/components/LeaderListItem/index.jsx
  src/components/TopLeaderCard/index.jsx
  src/containers/NavProfile.jsx
  src/containers/ProfileCard.jsx
  src/reducers/AuthReducer.js
  src/reducers/UserReducer.js
  src/storage.js
  src/utils.js
  src/utils/notifications.js
  src/utils/ranks.js
Labels: Issue: Feature, PR: Good to Merge

#118 Add logout
  src/actions/authActions.js
  src/actions/leaderboardActions.js
  src/utils.js
Labels: Issue: Feature, PR: Good to Merge

#119 Connect events to API
  src/actions/eventsActions.js
  src/actions/types.js
  src/containers/PastEvents.jsx
  src/containers/UpcomingEvents.jsx
  src/reducers/EventsReducer.js
  src/utils.js
Labels: PR: Good to Merge

#120 Connect user profiles to API
  src/actions/userActions.js
  src/components/NavProfile/index.jsx
  src/components/ProfileCard/index.jsx
  src/containers/NavProfile.jsx
  src/containers/PastEvents.jsx
  src/containers/ProfileCard.jsx
  src/containers/UpcomingEvents.jsx
  src/reducers/UserReducer.js
  src/utils.js
Labels: Issue: Feature, PR: Good to Merge

#121 Registration Form UI Tweaks
  src/actions/eventsActions.js
  src/actions/leaderboardActions.js
  src/actions/registerActions.js
  src/components/RegisterForm/index.jsx
  src/containers/RegisterForm.jsx
Labels: Issue: Feature, PR: Good to Merge

#122 Randomly generate leaderboard profile pic
  src/containers/FourAndMore.jsx
  src/containers/TopThree.jsx
  src/utils.js
Labels: Issue: Feature, PR: Good to Merge

#123 Finalize features before kickoff
  public/favicon.ico
  public/index.html
  src/actions/adminActions.js
  src/actions/eventsActions.js
  src/actions/types.js
  src/components/CreateEventForm/index.jsx
  src/components/Modal/index.jsx
  src/components/Modal/style.less
  src/components/PageLayout/index.jsx
  src/config.js
  src/containers/CheckInModal.jsx
  src/containers/CreateEventForm.jsx
  src/reducers/EventsReducer.js
  src/utils.js
Labels: Issue: Feature, PR: Good to Merge

#124 Fix production URL
  src/config.js
Labels: Issue: Bug, PR: Good to Merge

#125 Use environment to determine URL for API instead
  src/config.js
Labels: Issue: Bug, PR: Good to Merge

#126 Toml file
  netlify.toml
Labels: Issue: Setup, PR: Good to Merge

#127 Proxy add
  package.json
Labels: PR: Good to Merge

#128 Fix dates on event creation
  src/components/CreateEventForm/index.jsx
  src/containers/CreateEventForm.jsx
  src/utils.js
Labels: Issue: Feature, PR: Good to Merge
