Repository acmucsd/membership-portal-ui, pull requests merged in 2020-04, with the labels that each got.

#185 Profile uploads
  package-lock.json
  package.json
  src/actions/profileActions.js
  src/components/NavProfile/index.jsx
  src/components/ProfileCard/index.jsx
  src/components/ProfilePage/index.jsx
  src/components/ProfileUpdate/index.jsx
  src/components/ProfileUpdate/style.less
  src/config.js
  src/containers/FourAndMore.jsx
  src/containers/NavProfile.jsx
  src/containers/ProfileCard.jsx
  src/containers/TopThree.jsx
  src/reducers/LeaderboardReducer.js
  src/reducers/UserReducer.js
Labels: PR: Good to Merge, PR: Reviewed w/ Comments

#187 Dependency Bumps
  package.json
  yarn.lock
Labels: Issue: Dependencies, PR: Needs Review

#188 Home Page: Fixed H2 Text Overlap (Closes #132)
  src/components/EventCard/index.jsx
  src/components/EventCard/styles.less
  src/styles/vars.less
Labels: Issue: Bug, PR: Needs Review

#183 Email verification
  src/actions/authActions.js
  src/components/EmailVerificationPage/index.jsx
  src/components/EmailVerificationPage/style.less
  src/components/ResendEmailVerificationPage/index.jsx
  src/components/ResendEmailVerificationPage/style.less
  src/config.js
  src/containers/EmailVerificationPage.jsx
  src/containers/PageLayout.jsx
  src/containers/ResendEmailVerificationPage.jsx
  src/containers/requireStandardAccess.jsx
  src/index.js
Labels: PR: Good to Merge

#203 Fix Event Points White Border
  src/components/EventCard/index.jsx
  src/components/EventCard/styles.less
Labels: PR: Good to Merge

#204 Maintain Proper Past Events Order
  src/actions/eventsActions.js
  src/containers/PastEvents.jsx
Labels: PR: Good to Merge
