Repository acmucsd/membership-portal-ui, pull requests merged in 2020-05, with the labels that each got.

#207 Sl/new names
  src/utils.js
Labels: PR: Needs Review

#219 Fix Firefox Layout Issue
  src/components/NavProfile/style.less
Labels: PR: Good to Merge

#221 Use Dev Backend on Heroku
  src/config.js
Labels: PR: Good to Merge

#225 Use Dynamic Leaderboard Layout
  src/components/LeaderListItem/index.jsx
  src/components/LeaderListItem/style.less
Labels: PR: Good to Merge

#229 Package.json rename ant-demo -> membership-portal-ui
  package.json
Labels: Issue: Setup

#226 Clickable Profile Card
  src/components/ProfileCard/index.jsx
Labels: PR: Good to Merge

#234 Prevent Popup Menu from Scrolling
  src/components/NavProfile/index.jsx
Labels: PR: Good to Merge

#233 Make Online Locations Clickable
  src/components/EventCard/index.jsx
  src/components/EventCard/styles.less
  src/utils.js
Labels: PR: Good to Merge

#237 Change Profile Link to OnClick Event
  src/components/ProfileCard/index.jsx
Labels: PR: Good to Merge

#252 Add Google Analytics
  package-lock.json
  package.json
  src/index.js
  src/store.js
Labels: PR: Good to Merge

#254 Added event handler for discard button
  src/components/EditEventForm/index.jsx
Labels: PR: Good to Merge

#255 Automatically Lint Staged Files on Commit
  package-lock.json
  package.json
  yarn.lock
Labels: PR: Good to Merge

#261 Revert "Automatically Lint Staged Files on Commit"
  package-lock.json
  package.json
  yarn.lock
Labels: PR: Good to Merge

#260 Nightly Merge Master Bump 1.1.0
  package-lock.json
  package.json
  src/components/EditEventForm/index.jsx
  src/index.js
  src/store.js
Labels: PR: Good to Merge

#273 Use Banner from AWS
  package-lock.json
  package.json
  src/actions/bannerActions.js
  src/components/Banner/index.jsx
  src/components/PageLayout/index.jsx
  src/config.js
  src/containers/Banner.jsx
  src/reducers/BannerReducer.js
  src/reducers/index.js
  yarn.lock
Labels: PR: Good to Merge

#277 Restore Promises and Fix Package Lock
  .eslintrc.js
  package-lock.json
  src/actions/adminActions.js
  src/actions/authActions.js
  src/actions/profileActions.js
  src/actions/userActions.js
Labels: PR: Good to Merge, PR: Urgent

#278 Add Stylelint for Less Files
  .stylelintrc.js
  package-lock.json
  package.json
  src/components/AdminPage/style.less
  src/components/AuthenticateCard/style.less
  src/components/EditEventForm/style.less
  src/components/EmailVerificationPage/style.less
  src/components/ErrorPage/style.less
  src/components/EventCard/styles.less
  src/components/EventCheckIn/style.less
  src/components/EventsList/style.less
  src/components/HomePage/style.less
  src/components/LeaderListItem/style.less
  src/components/Leaderboard/style.less
  src/components/NavBarHorizontal/style.less
  src/components/NavBarVertical/style.less
  src/components/NavDropdown/style.less
  src/components/NavProfile/style.less
  src/components/PageLayout/style.less
  src/components/PasswordReset/style.less
  src/components/ProfileCard/style.less
  src/components/ProfilePage/style.less
  src/components/ProfileUpdate/style.less
  src/components/RegisterForm/style.less
  src/components/ResendEmailVerificationPage/style.less
  src/components/SignInForm/style.less
  src/components/StorePage/style.less
  src/components/TopLeaderCard/style.less
  src/components/admin/AwardPointsForm/style.less
  src/components/admin/CreateEventForm/style.less
  src/containers/egg/BreadPage/style.less
  src/styles/fonts.less
  src/styles/mixins.less
  src/styles/reset.less
Labels: PR: Good to Merge

#283 Event Card: Add event time to Upcoming cards
  src/containers/UpcomingEvents.jsx
  src/utils.js
Labels: PR: Good to Merge

#274 Delete event feature added
  src/actions/adminActions.js
  src/actions/types.js
  src/components/EditEventForm/index.jsx
  src/components/EditEventForm/style.less
  src/containers/admin/EditEventForm.jsx
Labels: PR: Good to Merge

#284 Fix Styling Lint Issue
  src/components/EditEventForm/style.less
Labels: PR: Good to Merge

#289 Add button to Password Request
  src/components/PasswordForm/index.jsx
  src/components/PasswordForm/style.less
  src/containers/PasswordPage.jsx
Labels: PR: Good to Merge

#286 Use Discord's Widget
  package-lock.json
  package.json
  src/components/DiscordPage/index.jsx
  src/components/DiscordPage/style.less
  src/components/NavBarHorizontal/index.jsx
  src/components/NavBarVertical/index.jsx
  src/components/NavDropdown/index.jsx
  src/containers/DiscordPage.jsx
  src/index.js
Labels: PR: Good to Merge

#251 Graduation Year update visual bug
  src/components/ProfileUpdate/index.jsx
  src/components/RegisterForm/index.jsx
  src/containers/RegisterForm.jsx
Labels: PR: Good to Merge

#292 Use Dynamic Banner Sizes
  src/actions/types.js
  src/components/Banner/index.jsx
  src/config.js
Labels: PR: Good to Merge

#294 Fix Event Card Image Ratio
  src/components/EventCard/styles.less
Labels: PR: Good to Merge
