Repository acmucsd/membership-portal-ui, pull requests merged in 2021-12, with the labels that each got.

#481 Cart Restructure
  src/store/components/ItemPage/index.tsx
  src/store/components/NavigationBar/index.tsx
  src/store/storeActions.ts
  src/store/storeReducer.ts
  src/types.ts
Labels: PR: Needs Review

#482 Cart updates
  src/store/components/ItemPage/index.tsx
  src/store/components/OptionSelector/index.tsx
  src/store/storeReducer.ts
  src/types.ts
Labels: PR: Needs Review, Store

#485 Proper Google Font Loading
  .stylelintrc.js
  public/index.html
  src/admin/components/AddAttendanceForm/style.less
  src/admin/components/AwardPointsForm/style.less
  src/admin/components/CreateEventForm/style.less
  src/admin/components/EditEventForm/style.less
  src/auth/components/AuthenticateCard/style.less
  src/auth/components/PasswordForm/style.less
  src/auth/components/PasswordReset/style.less
  src/auth/components/RegisterForm/style.less
  src/auth/components/SignInForm/style.less
  src/event/components/EventCard/styles.less
  src/event/components/EventCheckIn/style.less
  src/layout/components/DiscordPage/style.less
  src/layout/components/Header/style.less
  src/layout/components/HomePage/style.less
  src/layout/components/NavBarVertical/style.less
  src/layout/components/NavDropdown/style.less
  src/layout/components/NavListItem/style.less
  src/layout/components/NavProfile/style.less
  src/layout/components/PageLayout/style.less
  src/leaderboard/components/LeaderListItem/style.less
  src/leaderboard/components/LeaderPage/style.less
  src/leaderboard/components/TopLeaderCard/style.less
  src/profile/components/ProfileCard/style.less
  src/profile/components/ProfileUpdate/style.less
  src/styles/fonts.less
Labels: PR: Needs Review

#488 Wrong Year
  src/store/components/StorePage/index.tsx
Labels: PR: Needs Review

#486 Checkout Page
  src/config.ts
  src/store/components/CartDisplay/index.tsx
  src/store/components/CartDisplay/style.less
  src/store/components/CartPage/index.tsx
  src/store/components/CartPage/style.less
  src/store/components/ItemPage/index.tsx
  src/store/components/StoreCheckbox/style.less
  src/store/containers/CartPage.tsx
  src/store/containers/ItemPage.tsx
  src/types.ts
Labels: PR: Good to Merge

#493 Admin Collection Page
  src/store/components/AdminCollectionPage/index.tsx
  src/store/components/AdminCollectionPage/style.less
  src/store/components/StoreButton/index.tsx
  src/store/components/StoreColorInput/index.tsx
  src/store/components/StoreTextInput/index.tsx
Labels: PR: Needs Review

#495 added orders and order page
  src/store/components/OrderPage/index.tsx
  src/store/components/OrderPage/style.less
  src/store/components/OrdersPage/index.tsx
  src/store/components/OrdersPage/style.less
Labels: PR: Needs Review

#496 Added almost all of the fields for create item
  src/store/components/AdminItemPage/index.tsx
  src/store/components/AdminItemPage/style.less
  src/store/components/StoreCheckbox/index.tsx
Labels: PR: Needs Review

#498 Admin: Edit Event Page
  src/admin/components/EditEventForm/index.tsx
  src/admin/components/EditEventForm/style.less
  src/types.ts
Labels: PR: Good to Merge

#499 Made the plus button smaller
  src/store/components/ItemCard/index.tsx
  src/store/components/ItemCard/style.less
Labels: PR: Needs Review

#500 Add admin fulfill page
  src/store/components/AdminFulfillPage/index.tsx
  src/store/components/AdminFulfillPage/style.less
  src/store/containers/AdminFulfillPage.tsx
Labels: PR: Good to Merge

#501 Added Modal for the fulfill orders page
  src/store/components/AdminFulfillPage/index.tsx
  src/store/components/StoreImageUpload/index.tsx
Labels: PR: Needs Review

#504 Increase Layout Padding
  src/layout/components/PageLayout/style.less
  src/store/components/AdminCollectionPage/style.less
  src/store/components/AdminFulfillPage/style.less
  src/store/components/AdminItemPage/style.less
  src/store/components/AdminPickupPage/style.less
  src/store/components/AdminPreparePage/style.less
  src/store/components/CartPage/style.less
  src/store/components/ItemPage/style.less
  src/store/components/OrderPage/style.less
  src/store/components/OrdersPage/style.less
  src/store/components/StoreAdminPage/style.less
  src/store/components/StorePage/style.less
Labels: PR: Needs Review

#505 Admin Form Validation
  src/store/components/AdminCollectionPage/index.tsx
  src/store/components/AdminItemPage/index.tsx
  src/store/components/OptionDisplay/index.tsx
  src/store/components/StoreDropdown/index.tsx
  src/store/components/StoreDropdown/style.less
  src/store/components/StoreImageUpload/index.tsx
  src/store/components/StoreImageUpload/style.less
  src/store/components/StoreTextInput/index.tsx
  src/store/components/StoreTextInput/style.less
Labels: PR: Reviewed w/ Comments
