Repository acmucsd/membership-portal-ui, pull requests merged in 2022-02, with the labels that each got.

#533 Update README versions and deploy guide
  README.md
Labels: Issue: Documentation, PR: Good to Merge

#543 Independent History
  package.json
  src/auth/authActions.ts
  src/auth/containers/RegisterForm.tsx
  src/auth/containers/SignInForm.tsx
  src/auth/containers/requireAdminAuth.tsx
  src/auth/containers/requireAuth.tsx
  src/auth/containers/requireStoreAccess.tsx
  src/event/containers/CheckInHandler.tsx
  src/history.ts
  src/index.tsx
  src/redux_reducers.ts
  src/redux_store.ts
  src/store/components/AdminCollectionPage/index.tsx
  src/store/components/AdminItemPage/index.tsx
  src/store/components/AdminPickupPage/index.tsx
  src/store/components/CheckoutPage/index.tsx
  src/store/containers/CartPage.tsx
  yarn.lock
Labels: PR: Needs Review

#538 Update Leaderboard Loading Messages
  src/leaderboard/components/LeaderPage/index.tsx
  src/leaderboard/leaderboardReducer.ts
Labels: PR: Needs Review

#539 Auth route rewrite
  src/auth/containers/protectRoute.tsx
  src/auth/containers/requireAdminAuth.tsx
  src/auth/containers/requireAuth.tsx
  src/auth/containers/requireStoreAccess.tsx
  src/index.tsx
Labels: Issue: Bug, PR: Good to Merge, PR: Needs Review
