Repository acmucsd/membership-portal-ui, pull requests merged in 2023-02, with the labels that each got.

#604 Improve authorization for hidden store items
  src/store/components/ItemPage/index.tsx
Labels: PR: Good to Merge, PR: Needs Review

#599 Resume upload user side
  src/assets/icons/upload-done-icon.svg
  src/assets/icons/upload-icon.svg
  src/config.ts
  src/profile/components/ManageResume/index.tsx
  src/profile/components/ManageResume/style.less
  src/profile/components/ProfileUpdate/index.tsx
  src/profile/profileActions.ts
  src/types.ts
Labels: PR: Needs Review

#606 Delete label_ready_pr_to_merge.yml
  .github/workflows/label_ready_pr_to_merge.yml
Labels: PR: Needs Review

#601 Functional admin-side user resume table
  package.json
  src/admin/adminActions.ts
  src/admin/adminReducer.ts
  src/admin/adminTypes.ts
  src/admin/components/AdminPage/index.tsx
  src/admin/components/UserResumeTable/index.tsx
  src/admin/components/UserResumeTable/style.less
  src/admin/components/UserResumesPage/index.tsx
  src/admin/components/UserResumesPage/style.less
  src/admin/containers/UserResumesPage.tsx
  src/admin/containers/UserResumesTable.tsx
  src/config.ts
  src/index.tsx
  src/types.ts
  yarn.lock
Labels: PR: Good to Merge, PR: Needs Review

#607 Fix Add to Cart Broken Functionality
  src/store/components/ItemPage/index.tsx
Labels: Issue: Bug, PR: Needs Review, Priority: High

#590 Changed create and edit event facebook field to indicate not optional (#579)
  src/admin/containers/CreateEventForm.tsx
  src/admin/containers/EditEventForm.tsx
Labels: PR: Needs Review
